[STAKAN-111] Add Landing Page
Ankr-network/stkr-web3 pull request #264
Opened 2021-07-30 08:25 UTC by Kud8

Hello, brave developer, nice day to merge a pull request, ain't it?

## Follow the checklist to proceed

- [ ] I've performed a code self-review
- [ ] I've tested feature or bugfix on my own
- [ ] If I make changes to another person's module, I've asked how to use it or request a review
- [ ] I've checked mobile & tablet screens (if have changes in UI)
- [ ] Local build successfully completed
- [ ] Branch name and pull request title are according to [the requirements](https://ankrnetwork.atlassian.net/wiki/spaces/STAKAN/pages/1666646162/Branches+and+pull+request+naming)

2021-07-30 10:41 UTC, AndrewKhizhnyak commented on src/modules/landing/components/App/App.tsx
> +    setIsMenuOpened(v => !v);
```suggestion
    setIsMenuOpened(isMenuOpened => !isMenuOpened);
```

plz make ur code more readable for others

2021-07-30 10:43 UTC, AndrewKhizhnyak commented on src/modules/landing/components/App/App.tsx
> +  };
```suggestion

```
toggle should be enough

2021-07-30 10:45 UTC, AndrewKhizhnyak commented
Why is all text not in en-us? Don't we want to support i18n here?

2021-07-30 10:46 UTC, AndrewKhizhnyak commented on src/modules/landing/components/FAQ/FAQ.tsx
> +        winning Parachain Slot Auctions, meaning that Parachain Bonds are like
i18n

2021-07-30 10:47 UTC, AndrewKhizhnyak commented on src/modules/landing/components/FAQItem/FAQ.tsx
> +  const handleToggleAnswer = () => setIsOpened(v => !v);
```suggestion
  const handleToggleAnswer = () => setIsOpened(!isOpened);
```

2021-07-30 10:48 UTC, AndrewKhizhnyak commented on src/modules/landing/components/Footer/Footer.tsx
> +        ©2021 Ankr Staking. All rights reserved
i18n

2021-07-30 10:48 UTC, AndrewKhizhnyak commented on src/modules/landing/components/Info/Info.tsx
> +          Escrow Wallet
i18n

2021-07-30 10:49 UTC, AndrewKhizhnyak commented on src/modules/landing/components/InfoItem/InfoItem.tsx
> +          ) : null}
```suggestion
          {isShow && (
            <>
              <div className={classes.value}>
                <AnimatedNumber
                  animateToNumber={value}
                  includeComma
                  config={{ tension: 150, friction: 40 }}
                />
              </div>
              <div className={classes.description}>{children}</div>
            </>
          )}
```

2021-07-30 10:49 UTC, AndrewKhizhnyak commented on src/modules/landing/components/Menu/Menu.tsx
> +    // @ts-ignore
why ignore?

2021-07-30 10:50 UTC, AndrewKhizhnyak commented on src/modules/landing/components/SectionWrapper/SectionWrapper.tsx
> +      if (needTimeout === true) {
```suggestion
      if (needTimeout) {
```

2021-07-30 10:51 UTC, AndrewKhizhnyak requested changes
need changes

2021-07-30 20:35 UTC, Kud8 commented
> Why is all text not in en-us? Don't we want to support i18n here?

No

2021-07-30 20:43 UTC, Kud8 commented on src/modules/landing/components/Info/Info.tsx
> +          Escrow Wallet
We don't use it here

2021-07-30 20:43 UTC, Kud8 commented on src/modules/landing/components/Footer/Footer.tsx
> +        ©2021 Ankr Staking. All rights reserved
We don't use it here

2021-07-30 20:45 UTC, Kud8 commented on src/modules/landing/components/FAQItem/FAQ.tsx
> +  const handleToggleAnswer = () => setIsOpened(v => !v);
setState is asynchronous so we should use callback in toggle - it is best practice

2021-07-30 20:45 UTC, Kud8 commented on src/modules/landing/components/App/App.tsx
> +    setIsMenuOpened(v => !v);
setState is asynchronous so we should use callback in toggle - it is best practice

2021-08-02 08:40 UTC, AndrewKhizhnyak approved these changes

2021-08-02 10:07 UTC, merged